#!/usr/bin/env python3
"""Audit creature catalog: bedrock_geo vs gltf_skeleton backends and Luanti provenance."""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

import yaml

TOOLS = Path(__file__).resolve().parent
ROOT = TOOLS.parent
MODELS = ROOT / "models" / "creatures"
DOCS = ROOT / "docs"
YAML_SOURCES = TOOLS / "creature_luanti_sources.yaml"

sys.path.insert(0, str(TOOLS))
from luanti_mob_animation import (  # noqa: E402
    find_species_lua,
    load_mob_properties,
    resolve_b3d_model_path,
)

try:
    from PIL import Image
except ImportError:
    Image = None  # type: ignore


def load_yaml_sources() -> dict:
    if not YAML_SOURCES.is_file():
        return {}
    data = yaml.safe_load(YAML_SOURCES.read_text(encoding="utf-8")) or {}
    return data.get("species") or {}


def texture_alpha_frac(path: Path) -> float | None:
    if Image is None or not path.is_file():
        return None
    im = Image.open(path).convert("RGBA")
    px = list(im.getdata())
    if not px:
        return 0.0
    return sum(1 for *_, a in px if a < 250) / len(px)


def gltf_has_skin(gltf_path: Path) -> bool:
    if not gltf_path.is_file():
        return False
    gltf = json.loads(gltf_path.read_text(encoding="utf-8"))
    return bool(gltf.get("skins"))


def gltf_anim_names(gltf_path: Path) -> list[str]:
    if not gltf_path.is_file():
        return []
    gltf = json.loads(gltf_path.read_text(encoding="utf-8"))
    return [a.get("name", "") for a in gltf.get("animations", [])]


def audit_species(species_id: str, yaml_entry: dict) -> dict:
    species_dir = MODELS / species_id
    creature = json.loads((species_dir / "creature.json").read_text(encoding="utf-8"))
    visual = creature.get("visual", {})
    backend = visual.get("backend", "")
    habitat = creature.get("habitat", "")

    has_geo = (species_dir / "geometry.geo.json").is_file()
    has_gltf = (species_dir / "model.gltf").is_file()
    has_parts = bool(visual.get("parts"))
    skinned = gltf_has_skin(species_dir / "model.gltf") if has_gltf else False
    anims = gltf_anim_names(species_dir / "model.gltf") if has_gltf else []

    lua_path = find_species_lua(species_id)
    props, _ = load_mob_properties(species_id)
    lua_visual = props.get("visual", "")
    lua_mesh = props.get("mesh", "")
    yaml_model = yaml_entry.get("model", "")
    resolved_b3d = resolve_b3d_model_path(species_id)
    b3d_on_disk = bool(resolved_b3d)

    body = species_dir / "textures" / "body.png"
    body_alpha = texture_alpha_frac(body)

    issues: list[str] = []
    if backend == "gltf_skeleton" and not has_gltf:
        issues.append("missing_model_gltf")
    if backend in ("skeletal_geo", "bedrock_geo") and not has_geo:
        issues.append("missing_geometry_geo")
    if backend == "gltf_skeleton" and skinned and "inverseBindMatrices" not in json.dumps(
        json.loads((species_dir / "model.gltf").read_text(encoding="utf-8"))
    ):
        issues.append("skin_missing_ibm")
    if lua_visual == "sprite" and yaml_model:
        issues.append("sprite_with_b3d_yaml")
    if lua_visual == "mesh" and lua_mesh and not yaml_model and not b3d_on_disk:
        issues.append("b3d_lua_no_yaml")
    if species_id == "octopus" and lua_path is None:
        issues.append("blocked_no_marinaramobs")
    if species_id == "fire_spirit" and lua_visual == "sprite":
        issues.append("sprite_visual_policy")

    mesh_source = "none"
    if backend == "skeletal_geo":
        mesh_source = "bedrock_geo"
    elif skinned:
        mesh_source = "b3d_skinned"
    elif has_gltf:
        mesh_source = "parts_box_gltf"

    return {
        "id": species_id,
        "backend": backend,
        "habitat": habitat,
        "has_geo": has_geo,
        "has_gltf": has_gltf,
        "skinned": skinned,
        "mesh_source": mesh_source,
        "gltf_anims": anims,
        "lua_mod": lua_path.parent.name if lua_path else "",
        "lua_visual": lua_visual,
        "lua_mesh": lua_mesh,
        "yaml_model": yaml_model,
        "b3d_resolved": resolved_b3d or "",
        "b3d_on_disk": b3d_on_disk,
        "body_alpha": round(body_alpha, 4) if body_alpha is not None else None,
        "issues": issues,
    }


def write_matrix(rows: list[dict], summary: dict) -> None:
    lines = [
        "# Creature backend matrix",
        "",
        "Auto-generated by `tools/audit_creature_backends.py`.",
        "",
        "## Summary",
        "",
        f"- Species: **{summary['total']}**",
        f"- `bedrock_geo`: **{summary['bedrock_geo']}**",
        f"- `gltf_skeleton`: **{summary['gltf_skeleton']}**",
        f"- `rigid_voxels`: **{summary['rigid_voxels']}**",
        f"- Skinned glTF (BONE weights): **{summary['skinned']}**",
        f"- Parts-only glTF: **{summary['parts_gltf']}**",
        f"- Luanti b3d on disk in research: **{summary['b3d_on_disk']}**",
        f"- Rows with issues: **{summary['issue_rows']}**",
        "",
        "## By mesh source",
        "",
    ]
    for src, count in sorted(summary["by_mesh_source"].items()):
        lines.append(f"- `{src}`: {count}")
    lines.extend(
        [
            "",
            "## Species",
            "",
            "| id | backend | mesh_source | skinned | lua visual | b3d yaml | b3d disk | glTF anims | issues |",
            "|----|---------|-------------|---------|------------|----------|----------|------------|--------|",
        ]
    )
    for r in sorted(rows, key=lambda x: x["id"]):
        issues = ", ".join(r["issues"]) if r["issues"] else "—"
        anims = ", ".join(r["gltf_anims"][:4]) or "—"
        if len(r["gltf_anims"]) > 4:
            anims += ", …"
        lines.append(
            f"| {r['id']} | {r['backend']} | {r['mesh_source']} | {r['skinned']} | "
            f"{r['lua_visual'] or '—'} | {bool(r['yaml_model'])} | {r['b3d_on_disk']} | "
            f"{anims} | {issues} |"
        )
    lines.append("")
    path = DOCS / "CREATURE_BACKEND_MATRIX.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {path}")


def main() -> int:
    yaml_sources = load_yaml_sources()
    species_ids = sorted(
        p.name for p in MODELS.iterdir() if (p / "creature.json").is_file()
    )
    rows = [audit_species(sid, yaml_sources.get(sid, {})) for sid in species_ids]
    issue_rows = sum(1 for r in rows if r["issues"])
    summary = {
        "total": len(rows),
        "bedrock_geo": sum(
            1 for r in rows if r["backend"] in ("bedrock_geo", "skeletal_geo")
        ),
        "gltf_skeleton": sum(1 for r in rows if r["backend"] == "gltf_skeleton"),
        "rigid_voxels": sum(1 for r in rows if r["backend"] == "rigid_voxels"),
        "skinned": sum(1 for r in rows if r["skinned"]),
        "parts_gltf": sum(
            1 for r in rows if r["backend"] == "gltf_skeleton" and not r["skinned"]
        ),
        "b3d_on_disk": sum(1 for r in rows if r["b3d_on_disk"]),
        "issue_rows": issue_rows,
        "by_mesh_source": dict(Counter(r["mesh_source"] for r in rows)),
    }
    write_matrix(rows, summary)

    hard_fail = [
        r
        for r in rows
        if any(
            i in r["issues"]
            for i in ("missing_model_gltf", "missing_geometry_geo", "skin_missing_ibm")
        )
    ]
    if hard_fail:
        print(f"FAIL: {len(hard_fail)} species with asset/backend mismatch", file=sys.stderr)
        for r in hard_fail:
            print(f"  {r['id']}: {r['issues']}", file=sys.stderr)
        return 1
    print(f"audit_creature_backends: {len(rows)} species, {issue_rows} with policy flags")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
