#!/usr/bin/env python3
"""Static spawn diagnostics for all creature species."""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

import yaml

TOOLS = Path(__file__).resolve().parent
ROOT = TOOLS.parent
MODELS = ROOT / "models" / "creatures"
DOCS = ROOT / "docs"
PLAYER_EYE_HEIGHT = 1.62


def load_creature(species_dir: Path) -> dict:
    return json.loads((species_dir / "creature.json").read_text(encoding="utf-8"))


def terrestrial_risk(error: float) -> str:
    ae = abs(error)
    if ae > 0.4:
        return "high"
    if ae > 0.15:
        return "medium"
    return "low"


def expected_fail_reason(habitat: str, error: float, large: bool, spawnable: bool) -> str:
    if not spawnable:
        return "not_spawnable"
    if habitat == "terrestrial":
        if error > 0.4:
            return "eye_offset_probe"
        if error < -0.15:
            return "probe_in_blocks"
        return "ok_or_collision"
    if habitat == "aquatic":
        if large:
            return "aquatic_depth_or_column"
        return "fluid_column_xz"
    if habitat == "aerial":
        return "aerial_lift_or_clearance"
    if habitat == "amphibious":
        return "land_eye_offset_or_water_column"
    if habitat == "lava":
        return "lava_column_xz"
    return "unknown"


def diagnose_species(creature: dict) -> dict:
    species_id = creature["id"]
    habitat = creature.get("habitat", "terrestrial")
    eye = float(creature.get("eye_height", PLAYER_EYE_HEIGHT))
    rest = creature.get("bounds", {}).get("rest", [1, 1, 1])
    volume = rest[0] * rest[1] * rest[2]
    large = max(rest) > 2.0
    spawnable = bool(creature.get("catalog", {}).get("spawnable", False))
    error = PLAYER_EYE_HEIGHT - eye
    row = {
        "id": species_id,
        "habitat": habitat,
        "spawnable": spawnable,
        "eye_height": eye,
        "eye_offset_error": round(error, 3),
        "terrestrial_risk": terrestrial_risk(error) if habitat == "terrestrial" else "n/a",
        "bounds_rest": rest,
        "bounds_volume": round(volume, 3),
        "large_collision": large,
        "expected_fail_reason": expected_fail_reason(habitat, error, large, spawnable),
    }
    issues = []
    if spawnable and habitat == "terrestrial" and error > 0.15:
        issues.append("spawn_probe")
    if spawnable and habitat == "aquatic" and large:
        issues.append("aquatic_depth")
    if spawnable and habitat == "aerial":
        issues.append("aerial_lift")
    if spawnable and habitat in ("aquatic", "amphibious", "lava"):
        issues.append("spawn_habitat")
    row["issues_suggested"] = issues
    return row


def write_markdown(rows: list[dict], path: Path) -> None:
    lines = [
        "# Creature spawn diagnosis",
        "",
        "Auto-generated by `tools/diagnose_creature_spawn.py`.",
        "",
        f"Player eye height assumed: **{PLAYER_EYE_HEIGHT}**",
        "",
        "| id | habitat | spawnable | eye_err | terrestrial_risk | large | expected_fail |",
        "|----|---------|-----------|---------|------------------|-------|---------------|",
    ]
    for r in rows:
        lines.append(
            f"| {r['id']} | {r['habitat']} | {r['spawnable']} | {r['eye_offset_error']} "
            f"| {r['terrestrial_risk']} | {r['large_collision']} | {r['expected_fail_reason']} |"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    species_dirs = sorted(
        p for p in MODELS.iterdir() if p.is_dir() and (p / "creature.json").is_file()
    )
    rows = [diagnose_species(load_creature(p)) for p in species_dirs]
    out_yaml = TOOLS / "creature_spawn_diagnosis.yaml"
    out_yaml.write_text(
        yaml.safe_dump({"species": {r["id"]: r for r in rows}}, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    write_markdown(rows, DOCS / "CREATURE_SPAWN_DIAGNOSIS.md")
    print(f"OK diagnosed {len(rows)} species -> {out_yaml.name}, CREATURE_SPAWN_DIAGNOSIS.md")


if __name__ == "__main__":
    main()
