#!/usr/bin/env python3
"""Generate docs/PREFAB_CATALOG.md from prefab JSON + manifest."""

from __future__ import annotations

import json
from pathlib import Path

import yaml

from prefab_bounds import format_size, prefab_bounds

REPO = Path(__file__).resolve().parents[1]
PREFABS = REPO / "prefabs"
MANIFEST = REPO / "tools" / "prefab_manifest.yaml"
OUT = REPO / "docs" / "PREFAB_CATALOG.md"


def main() -> int:
    manifest = yaml.safe_load(MANIFEST.read_text(encoding="utf-8")) or {}
    meta_by_name = manifest.get("prefabs") or {}

    rows: list[tuple[str, str, str, int, str, str, str, str]] = []
    for path in sorted(PREFABS.rglob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8-sig"))
        name = data.get("name") or path.stem
        meta = meta_by_name.get(name, {})
        blocks = data.get("blocks") or []
        bounds = prefab_bounds(blocks)
        wg = meta.get("worldgen") or {}
        pool = wg.get("pool") or "—"
        if wg.get("mode") == "scatter_blocks":
            pool = f"scatter:{wg.get('block', '?')}"
        rows.append(
            (
                name,
                data.get("displayName") or meta.get("displayName") or name,
                data.get("category") or meta.get("category") or "misc",
                len(blocks),
                format_size(bounds),
                pool,
                (meta.get("source") or {}).get("license", ""),
                meta.get("import_status", "ready"),
            )
        )

    lines = [
        "# Prefab catalog",
        "",
        "Auto-generated by `tools/generate_prefab_catalog.py`. Do not edit by hand.",
        "",
        f"Total prefabs: **{len(rows)}**",
        "",
        "| Name | Display | Category | Blocks | Size (WxHxD) | Worldgen | License | Status |",
        "|------|---------|----------|--------|--------------|----------|---------|--------|",
    ]
    for name, display, category, count, size, pool, license_, status in rows:
        lines.append(
            f"| `{name}` | {display} | {category} | {count} | {size} | {pool} | {license_} | {status} |"
        )
    lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
