#!/usr/bin/env python3
"""Generate docs/PREFAB_CATALOG.md from prefab JSON + manifest."""

from __future__ import annotations

import json
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
PREFABS = REPO / "prefabs"
MANIFEST = REPO / "tools" / "prefab_manifest.yaml"
OUT = REPO / "docs" / "PREFAB_CATALOG.md"


def main() -> int:
    manifest = yaml.safe_load(MANIFEST.read_text(encoding="utf-8")) or {}
    meta_by_name = manifest.get("prefabs") or {}

    rows: list[tuple[str, str, str, int, str, str]] = []
    for path in sorted(PREFABS.rglob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8-sig"))
        name = data.get("name") or path.stem
        meta = meta_by_name.get(name, {})
        rows.append(
            (
                name,
                data.get("displayName") or meta.get("displayName") or name,
                data.get("category") or meta.get("category") or "misc",
                len(data.get("blocks") or []),
                (meta.get("source") or {}).get("license", ""),
                meta.get("import_status", "ready"),
            )
        )

    lines = [
        "# Prefab catalog",
        "",
        "Auto-generated by `tools/generate_prefab_catalog.py`. Do not edit by hand.",
        "",
        f"Total prefabs: **{len(rows)}**",
        "",
        "| Name | Display | Category | Blocks | License | Status |",
        "|------|---------|----------|--------|---------|--------|",
    ]
    for name, display, category, count, license_, status in rows:
        lines.append(
            f"| `{name}` | {display} | {category} | {count} | {license_} | {status} |"
        )
    lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
