#!/usr/bin/env python3
"""Import curated CC0 item / armor glTF props into models/items/.

Educational helper: downloads (or copies from a local pack cache) third-party
CC0 meshes and places them next to Cubatarium parts[] fallbacks.

Supported upstream packs (all CC0 1.0):
  - Kenney Survival Kit     https://www.kenney.nl/assets/survival-kit
  - KayKit RPG Tools Bits   https://kaylousberg.itch.io/rpg-tools-bits
  - Quaternius Fantasy Props / Ultimate RPG Items
                            https://quaternius.com/

Usage:
  python tools/import_item_models.py --pack-root E:/asset_cache/kenney_survival-kit
  python tools/import_item_models.py --list

The default shipped content uses authored parts[] JSON under models/items/
(generated by this repo). Point content/items/*.json \"model\" at
models/items/<id>/model.gltf after a successful import to prefer glTF.
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODELS = ROOT / "models" / "items"
MANIFEST = ROOT / "tools" / "item_model_manifest.json"

# Mapping: cubatarium item id -> relative path inside an extracted pack.
# Paths are illustrative; adjust after inspecting a downloaded pack.
DEFAULT_MANIFEST = {
    "sources": [
        {
            "id": "kenney_survival_kit",
            "name": "Kenney Survival Kit",
            "license": "CC0-1.0",
            "url": "https://www.kenney.nl/assets/survival-kit",
        },
        {
            "id": "kaykit_rpg_tools",
            "name": "KayKit RPG Tools Bits",
            "license": "CC0-1.0",
            "url": "https://kaylousberg.itch.io/rpg-tools-bits",
        },
        {
            "id": "quaternius_fantasy_props",
            "name": "Quaternius Fantasy Props MegaKit / Ultimate RPG Items",
            "license": "CC0-1.0",
            "url": "https://quaternius.com/",
        },
    ],
    "items": {
        "iron_sword": {"source": "quaternius_fantasy_props", "glob": "**/Sword*.gltf"},
        "iron_axe": {"source": "kaykit_rpg_tools", "glob": "**/axe*.gltf"},
        "iron_pickaxe": {"source": "kaykit_rpg_tools", "glob": "**/pickaxe*.gltf"},
        "iron_shovel": {"source": "kenney_survival_kit", "glob": "**/shovel*.gltf"},
        "iron_hammer": {"source": "kaykit_rpg_tools", "glob": "**/hammer*.gltf"},
        "wood_bow": {"source": "quaternius_fantasy_props", "glob": "**/Bow*.gltf"},
        "leather_head": {"source": "quaternius_fantasy_props", "glob": "**/Helmet*.gltf"},
        "iron_head": {"source": "quaternius_fantasy_props", "glob": "**/Helmet*.gltf"},
        "iron_chest": {"source": "quaternius_fantasy_props", "glob": "**/Armor*.gltf"},
    },
}


def ensure_manifest() -> dict:
    if not MANIFEST.exists():
        MANIFEST.write_text(json.dumps(DEFAULT_MANIFEST, indent=2) + "\n", encoding="utf-8")
        return DEFAULT_MANIFEST
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def list_items(manifest: dict) -> None:
    print("Sources:")
    for s in manifest.get("sources", []):
        print(f"  - {s['name']} ({s['license']}): {s['url']}")
    print("\nCurated item mapping:")
    for item_id, spec in sorted(manifest.get("items", {}).items()):
        print(f"  {item_id}: source={spec.get('source')} glob={spec.get('glob')}")


def import_from_pack(pack_root: Path, manifest: dict, dry_run: bool) -> int:
    if not pack_root.is_dir():
        raise SystemExit(f"pack root not found: {pack_root}")
    copied = 0
    for item_id, spec in manifest.get("items", {}).items():
        matches = list(pack_root.glob(spec.get("glob", "")))
        if not matches:
            print(f"SKIP {item_id}: no match for {spec.get('glob')}")
            continue
        src = matches[0]
        dest_dir = MODELS / item_id
        dest = dest_dir / "model.gltf"
        print(f"{'DRY ' if dry_run else ''}COPY {src} -> {dest}")
        if not dry_run:
            dest_dir.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dest)
            # Copy sibling textures / .bin if present.
            for sib in src.parent.iterdir():
                if sib.suffix.lower() in {".bin", ".png", ".jpg", ".jpeg"}:
                    shutil.copy2(sib, dest_dir / sib.name)
            meta = {
                "id": item_id,
                "format": "gltf",
                "license": "CC0-1.0",
                "source": spec.get("source"),
                "upstream_file": str(src.relative_to(pack_root)).replace("\\", "/"),
            }
            (dest_dir / "ATTRIBUTION.json").write_text(
                json.dumps(meta, indent=2) + "\n", encoding="utf-8"
            )
        copied += 1
    return copied


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--list", action="store_true", help="List sources and mappings")
    parser.add_argument("--pack-root", type=Path, help="Extracted CC0 pack directory")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    manifest = ensure_manifest()
    if args.list or not args.pack_root:
        list_items(manifest)
        if not args.pack_root:
            print("\nPass --pack-root <extracted_pack> to copy matching glTF files.")
            return
    n = import_from_pack(args.pack_root, manifest, args.dry_run)
    print(f"Done. Imported {n} item model(s).")


if __name__ == "__main__":
    main()
