#!/usr/bin/env python3
"""Bulk style refactor: class U-prefix renames and member trailing_ -> PascalCase."""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "src"
SKIP_FILES = {"stb_image.h"}

# Longest names first to avoid partial replacements.
CLASS_RENAMES = [
    ("CreaturePosePresenterRegistry", "UCreaturePosePresenterRegistry"),
    ("TerrestrialBipedPosePresenter", "UTerrestrialBipedPosePresenter"),
    ("CreatureLocomotionController", "UCreatureLocomotionController"),
    ("CreatureDefinitionStorage", "UCreatureDefinitionStorage"),
    ("GreedyTransparentPipeline", "UGreedyTransparentPipeline"),
    ("ProceduralWorldGenFactory", "UProceduralWorldGenFactory"),
    ("WorldCreatureActivitySink", "UWorldCreatureActivitySink"),
    ("CreatureActivityDirector", "UCreatureActivityDirector"),
    ("CreatureActivityRegistry", "UCreatureActivityRegistry"),
    ("OverworldBiomesPipeline", "UOverworldBiomesPipeline"),
    ("BlockDefinitionStorage", "UBlockDefinitionStorage"),
    ("CreatureTextureStorage", "UCreatureTextureStorage"),
    ("OverworldHeightSampler", "UOverworldHeightSampler"),
    ("AndroidPlatformWindow", "UAndroidPlatformWindow"),
    ("ConsoleCommandHistory", "UConsoleCommandHistory"),
    ("CreativePaletteScreen", "UCreativePaletteScreen"),
    ("CreatureVisualFactory", "UCreatureVisualFactory"),
    ("DesktopPlatformWindow", "UDesktopPlatformWindow"),
    ("OverworldFullPipeline", "UOverworldFullPipeline"),
    ("SkinDefinitionStorage", "USkinDefinitionStorage"),
    ("AndroidPlatformPaths", "UAndroidPlatformPaths"),
    ("DesktopPlatformPaths", "UDesktopPlatformPaths"),
    ("TouchVirtualJoystick", "UTouchVirtualJoystick"),
    ("WorldGenSettingsForm", "UWorldGenSettingsForm"),
    ("ContentTypeRegistry", "UContentTypeRegistry"),
    ("CreatureVisualRigid", "UCreatureVisualRigid"),
    ("UiTexturedQuadBatch", "UGuiTexturedQuadBatch"),
    ("WanderActivityAgent", "UWanderActivityAgent"),
    ("CreatureAppearance", "UCreatureAppearance"),
    ("CreatureVisualGltf", "UCreatureVisualGltf"),
    ("LegacyHashPipeline", "ULegacyHashPipeline"),
    ("TextureBaseStorage", "UTextureBaseStorage"),
    ("TextureCubeStorage", "UTextureCubeStorage"),
    ("CreatureIconCache", "UCreatureIconCache"),
    ("CreatureInventory", "UCreatureInventory"),
    ("OverworldPipeline", "UOverworldPipeline"),
    ("TouchControlPanel", "UTouchControlPanel"),
    ("GuiTouchControls", "UGuiTouchControls"),
    ("TouchInputBridge", "UTouchInputBridge"),
    ("CommandRegistry", "UCommandRegistry"),
    ("InGameHudScreen", "UInGameHudScreen"),
    ("LoadWorldScreen", "ULoadWorldScreen"),
    ("ObjectPrototype", "UObjectPrototype"),
    ("PrefabIconCache", "UPrefabIconCache"),
    ("TouchHoldButton", "UTouchHoldButton"),
    ("AnimationClock", "UAnimationClock"),
    ("AssetStreamBuf", "UAssetStreamBuf"),
    ("ChunkMeshCache", "UChunkMeshCache"),
    ("CreatureVisual", "UCreatureVisual"),
    ("GuiDialogFrame", "UGuiDialogFrame"),
    ("GuiInputRouter", "UGuiInputRouter"),
    ("MainMenuScreen", "UMainMenuScreen"),
    ("NewWorldScreen", "UNewWorldScreen"),
    ("SettingsScreen", "USettingsScreen"),
    ("WorldGenerator", "UWorldGenerator"),
    ("BlockRegistry", "UBlockRegistry"),
    ("ChunkStreamer", "UChunkStreamer"),
    ("ConsoleScreen", "UConsoleScreen"),
    ("GlfwClipboard", "UGlfwClipboard"),
    ("GuiIconSource", "UGuiIconSource"),
    ("GuiScreenBase", "UGuiScreenBase"),
    ("GuiScrollView", "UGuiScrollView"),
    ("NullClipboard", "UNullClipboard"),
    ("ObjectStorage", "UObjectStorage"),
    ("PrefabLibrary", "UPrefabLibrary"),
    ("ShaderManager", "UShaderManager"),
    ("ShaderProgram", "UShaderProgram"),
    ("BiomeSampler", "UBiomeSampler"),
    ("BlockRaycast", "UBlockRaycast"),
    ("ChunkManager", "UChunkManager"),
    ("FlatPipeline", "UFlatPipeline"),
    ("GlStateScope", "UGlStateScope"),
    ("GreedyMesher", "UGreedyMesher"),
    ("GuiPopupMenu", "UGuiPopupMenu"),
    ("GuiTextInput", "UGuiTextInput"),
    ("TerrainPlane", "UTerrainPlane"),
    ("TouchLookPad", "UTouchLookPad"),
    ("GameSession", "UGameSession"),
    ("GuiCheckbox", "UGuiCheckbox"),
    ("GuiListView", "UGuiListView"),
    ("GuiRenderer", "UGuiRenderer"),
    ("TextureBase", "UTextureBase"),
    ("TextureCube", "UTextureCube"),
    ("UiQuadBatch", "UGuiQuadBatch"),
    ("BlockWorld", "UBlockWorld"),
    ("GuiContext", "UGuiContext"),
    ("PrefabUtil", "UPrefabUtil"),
    ("SingleCube", "USingleCube"),
    ("GuiButton", "UGuiButton"),
    ("GuiLayout", "UGuiLayout"),
    ("GuiTabBar", "UGuiTabBar"),
    ("GuiWidget", "UGuiWidget"),
    ("GuiWindow", "UGuiWindow"),
    ("Creature", "UCreature"),
    ("GuiLabel", "UGuiLabel"),
    ("GuiPanel", "UGuiPanel"),
    ("GuiSlot", "UGuiSlot"),
    ("Terrain", "UTerrain"),
    ("Camera", "UCamera"),
    ("CubeGL", "UCubeGL"),
    ("Object", "UObject"),
    ("Person", "UPerson"),
    ("Player", "UPlayer"),
    ("Chunk", "UChunk"),
    ("Cube", "UCube"),
    ("Rect", "URect"),
    ("User", "UUser"),
]

# Members: old_suffix_name -> PascalCase (applied as word-boundary identifier)
MEMBER_RENAMES = [
    ("texture_base_storage_file_name", "TextureBaseStorageFileName"),
    ("texture_cube_storage_file_name", "TextureCubeStorageFileName"),
    ("preparedTransparentTextures_", "PreparedTransparentTextures"),
    ("suppressConsoleToggleChar_", "SuppressConsoleToggleChar"),
    ("blockInputCancelPending_", "BlockInputCancelPending"),
    ("deferredDragStartScroll_", "DeferredDragStartScroll"),
    ("object_storage_file_name", "ObjectStorageFileName"),
    ("entityCollisionEnabled_", "EntityCollisionEnabled"),
    ("releaseJoystickCapture_", "ReleaseJoystickCapture"),
    ("cameraBaselinePending_", "CameraBaselinePending"),
    ("hotbarCountValueLabel_", "HotbarCountValueLabel"),
    ("overlayPointerCapture_", "OverlayPointerCapture"),
    ("posePresenterRegistry_", "PosePresenterRegistry"),
    ("preparedTransparentVp_", "PreparedTransparentVp"),
    ("procedurallyGenerated_", "ProcedurallyGenerated"),
    ("suppressCharCodepoint_", "SuppressCharCodepoint"),
    ("transientMessageUntil_", "TransientMessageUntil"),
    ("controlledCreatureId_", "ControlledCreatureId"),
    ("greedyGpuTransparent_", "GreedyGpuTransparent"),
    ("hasIntersectionBlock_", "HasIntersectionBlock"),
    ("historyBrowseFromEnd_", "HistoryBrowseFromEnd"),
    ("intersectionBlockPos_", "IntersectionBlockPos"),
    ("lastCullMeshRevision_", "LastCullMeshRevision"),
    ("maxUnloadOpsPerFrame_", "MaxUnloadOpsPerFrame"),
    ("physicsSuspendFrames_", "PhysicsSuspendFrames"),
    ("placeClickMaxSeconds_", "PlaceClickMaxSeconds"),
    ("renderDistanceChunks_", "RenderDistanceChunks"),
    ("scrollPageMeasureFns_", "ScrollPageMeasureFns"),
    ("acceptKeyNavigation_", "AcceptKeyNavigation"),
    ("allowProceduralFill_", "AllowProceduralFill"),
    ("breakHoldMinSeconds_", "BreakHoldMinSeconds"),
    ("cachedInstanceCount_", "CachedInstanceCount"),
    ("collisionSizeBlocks_", "CollisionSizeBlocks"),
    ("controlSchemeButton_", "ControlSchemeButton"),
    ("creatureDefinitions_", "CreatureDefinitions"),
    ("deferredTouchActive_", "DeferredTouchActive"),
    ("depthTestWasEnabled_", "DepthTestWasEnabled"),
    ("keyboardInsetBottom_", "KeyboardInsetBottom"),
    ("lastCullCameraChunk_", "LastCullCameraChunk"),
    ("lastMoveIntentValid_", "LastMoveIntentValid"),
    ("loadedFromChunkSave_", "LoadedFromChunkSave"),
    ("locomotionArchetype_", "LocomotionArchetype"),
    ("movementDiagnostics_", "MovementDiagnostics"),
    ("scrollPageLayoutFns_", "ScrollPageLayoutFns"),
    ("thirdPersonDistance_", "ThirdPersonDistance"),
    ("viewportInsetBottom_", "ViewportInsetBottom"),
    ("windowResizeCallback", "WindowResizeCallback"),
    ("agentsByBehaviorId_", "AgentsByBehaviorId"),
    ("cachedMeshRevision_", "CachedMeshRevision"),
    ("contentInsetBottom_", "ContentInsetBottom"),
    ("controlSchemeLabel_", "ControlSchemeLabel"),
    ("deferredDragStartY_", "DeferredDragStartY"),
    ("greedyBatchesDirty_", "GreedyBatchesDirty"),
    ("lastMoveIntentTime_", "LastMoveIntentTime"),
    ("lastSpacePressTime_", "LastSpacePressTime"),
    ("maxLoadOpsPerFrame_", "MaxLoadOpsPerFrame"),
    ("mouseButtonCallback", "MouseButtonCallback"),
    ("mousePressedWidget_", "MousePressedWidget"),
    ("mouseScrollCallback", "MouseScrollCallback"),
    ("onSelectionChanged_", "OnSelectionChanged"),
    ("overlayMarginRight_", "OverlayMarginRight"),
    ("pendingSelectIndex_", "PendingSelectIndex"),
    ("proceduralSettings_", "ProceduralSettings"),
    ("programmaticChange_", "ProgrammaticChange"),
    ("releaseAllCaptures_", "ReleaseAllCaptures"),
    ("showPerformanceBox_", "ShowPerformanceBox"),
    ("viewportInsetRight_", "ViewportInsetRight"),
    ("worldSessionActive_", "WorldSessionActive"),
    ("activeWorldFolder_", "ActiveWorldFolder"),
    ("afterScrollLayout_", "AfterScrollLayout"),
    ("blockBatchesValid_", "BlockBatchesValid"),
    ("cameraBaselinePos_", "CameraBaselinePos"),
    ("clearShiftRequest_", "ClearShiftRequest"),
    ("contentInsetRight_", "ContentInsetRight"),
    ("defaultWorldInput_", "DefaultWorldInput"),
    ("defaultWorldLabel_", "DefaultWorldLabel"),
    ("default_world_name", "DefaultWorldName"),
    ("draggingSelection_", "DraggingSelection"),
    ("hotbarMinusButton_", "HotbarMinusButton"),
    ("lastMoveIntentDir_", "LastMoveIntentDir"),
    ("modelYawOffsetDeg_", "ModelYawOffsetDeg"),
    ("mouseJustReleased_", "MouseJustReleased"),
    ("pendingAssignment_", "PendingAssignment"),
    ("pendingMenuAction_", "PendingMenuAction"),
    ("quitDialogVisible_", "QuitDialogVisible"),
    ("rightDragExceeded_", "RightDragExceeded"),
    ("routeCapturedMove_", "RouteCapturedMove"),
    ("texturedQuadBatch_", "TexturedQuadBatch"),
    ("thirdPersonHeight_", "ThirdPersonHeight"),
    ("useSecondaryColor_", "UseSecondaryColor"),
    ("viewportInsetLeft_", "ViewportInsetLeft"),
    ("activityDirector_", "ActivityDirector"),
    ("blockDefinitions_", "BlockDefinitions"),
    ("cachedBlockCount_", "CachedBlockCount"),
    ("contentInsetLeft_", "ContentInsetLeft"),
    ("defaultUserInput_", "DefaultUserInput"),
    ("defaultUserLabel_", "DefaultUserLabel"),
    ("default_user_name", "DefaultUserName"),
    ("generateColumnFn_", "GenerateColumnFn"),
    ("hasPersistedSave_", "HasPersistedSave"),
    ("hotbarCountLabel_", "HotbarCountLabel"),
    ("hotbarPlusButton_", "HotbarPlusButton"),
    ("mouseJustPressed_", "MouseJustPressed"),
    ("mouseMoveCallback", "MouseMoveCallback"),
    ("overlayMarginTop_", "OverlayMarginTop"),
    ("overlayTintAlpha_", "OverlayTintAlpha"),
    ("overlayTintColor_", "OverlayTintColor"),
    ("pendingEnterGame_", "PendingEnterGame"),
    ("playerCreatureId_", "PlayerCreatureId"),
    ("prevMouseButtons_", "PrevMouseButtons"),
    ("smoothedFogColor_", "SmoothedFogColor"),
    ("stencilValueMask_", "StencilValueMask"),
    ("stencilWriteMask_", "StencilWriteMask"),
    ("streamingEnabled_", "StreamingEnabled"),
    ("suppressNextJump_", "SuppressNextJump"),
    ("transientMessage_", "TransientMessage"),
    ("uiPointerCapture_", "UiPointerCapture"),
    ("verticalVelocity_", "VerticalVelocity"),
    ("viewportInsetTop_", "ViewportInsetTop"),
    ("activeSlotIndex_", "ActiveSlotIndex"),
    ("blendWasEnabled_", "BlendWasEnabled"),
    ("blockWorldReady_", "BlockWorldReady"),
    ("commandRegistry_", "CommandRegistry"),
    ("consoleKeyInput_", "ConsoleKeyInput"),
    ("consoleKeyLabel_", "ConsoleKeyLabel"),
    ("contentInsetTop_", "ContentInsetTop"),
    ("creatureEntries_", "CreatureEntries"),
    ("crouchUpperDrop_", "CrouchUpperDrop"),
    ("deferredDragged_", "DeferredDragged"),
    ("dragStartScroll_", "DragStartScroll"),
    ("greedyGpuOpaque_", "GreedyGpuOpaque"),
    ("inventoryButton_", "InventoryButton"),
    ("locomotionFacts_", "LocomotionFacts"),
    ("locomotionState_", "LocomotionState"),
    ("overlayCaptures_", "OverlayCaptures"),
    ("paletteKeyInput_", "PaletteKeyInput"),
    ("paletteKeyLabel_", "PaletteKeyLabel"),
    ("pendingPlacePos_", "PendingPlacePos"),
    ("pendingPlaceTap_", "PendingPlaceTap"),
    ("playerCharacter_", "PlayerCharacter"),
    ("renderDistInput_", "RenderDistInput"),
    ("renderDistLabel_", "RenderDistLabel"),
    ("rightLookActive_", "RightLookActive"),
    ("selectedEntryId_", "SelectedEntryId"),
    ("skinDefinitions_", "SkinDefinitions"),
    ("smoothedSkyTint_", "SmoothedSkyTint"),
    ("spaceWasPressed_", "SpaceWasPressed"),
    ("worldFolderPath_", "WorldFolderPath"),
    ("activeBarIndex_", "ActiveBarIndex"),
    ("animationClock_", "AnimationClock"),
    ("blockedRegions_", "BlockedRegions"),
    ("commandHistory_", "CommandHistory"),
    ("configFilePath_", "ConfigFilePath"),
    ("contentCatalog_", "ContentCatalog"),
    ("contentOffsetX_", "ContentOffsetX"),
    ("contentOffsetY_", "ContentOffsetY"),
    ("drawBackground_", "DrawBackground"),
    ("focusHighlight_", "FocusHighlight"),
    ("frametimeTicks_", "FrametimeTicks"),
    ("generatorLabel_", "GeneratorLabel"),
    ("hasLastPlayerY_", "HasLastPlayerY"),
    ("hasPlaceTarget_", "HasPlaceTarget"),
    ("instancesDirty_", "InstancesDirty"),
    ("joystickActive_", "JoystickActive"),
    ("lastBodyOrigin_", "LastBodyOrigin"),
    ("lastFrameStats_", "LastFrameStats"),
    ("mainMenuScreen_", "MainMenuScreen"),
    ("maxHeightInput_", "MaxHeightInput"),
    ("maxHeightLabel_", "MaxHeightLabel"),
    ("modifiedChunks_", "ModifiedChunks"),
    ("nextCreatureId_", "NextCreatureId"),
    ("overlayBlockId_", "OverlayBlockId"),
    ("renderDistance_", "RenderDistance"),
    ("renderSettings_", "RenderSettings"),
    ("scrollOffsetPx_", "ScrollOffsetPx"),
    ("secondarySlots_", "SecondarySlots"),
    ("showPerformance", "ShowPerformance"),
    ("activeTexture_", "ActiveTexture"),
    ("batchCacheBox_", "BatchCacheBox"),
    ("blockRegistry_", "BlockRegistry"),
    ("consoleButton_", "ConsoleButton"),
    ("consoleScreen_", "ConsoleScreen"),
    ("contentHeight_", "ContentHeight"),
    ("controlScheme_", "ControlScheme"),
    ("creatureCache_", "CreatureCache"),
    ("dirtyChunkSet_", "DirtyChunkSet"),
    ("featureParams_", "FeatureParams"),
    ("footerButtons_", "FooterButtons"),
    ("frameDuration_", "FrameDuration"),
    ("greedyBatches_", "GreedyBatches"),
    ("heightSampler_", "HeightSampler"),
    ("hoveredWidget_", "HoveredWidget"),
    ("inventoryMode_", "InventoryMode"),
    ("keyboardFocus_", "KeyboardFocus"),
    ("layoutPadding_", "LayoutPadding"),
    ("layoutSpacing_", "LayoutSpacing"),
    ("modalKeyboard_", "ModalKeyboard"),
    ("mousePosition_", "MousePosition"),
    ("objectEntries_", "ObjectEntries"),
    ("paletteScreen_", "PaletteScreen"),
    ("placeBlockPos_", "PlaceBlockPos"),
    ("prefabLibrary_", "PrefabLibrary"),
    ("pressedInside_", "PressedInside"),
    ("quitRequested_", "QuitRequested"),
    ("quitYesButton_", "QuitYesButton"),
    ("scrollbarMode_", "ScrollbarMode"),
    ("seaLevelInput_", "SeaLevelInput"),
    ("seaLevelLabel_", "SeaLevelLabel"),
    ("selectedIndex_", "SelectedIndex"),
    ("shaderManager_", "ShaderManager"),
    ("stepUpEnabled_", "StepUpEnabled"),
    ("touchControls_", "TouchControls"),
    ("unloadChunkFn_", "UnloadChunkFn"),
    ("verboseLogging", "VerboseLogging"),
    ("verticalLabel_", "VerticalLabel"),
    ("WorldInstance", "WorldInstance"),
    ("activeScreen_", "ActiveScreen"),
    ("activeTypeId_", "ActiveTypeId"),
    ("baseSkyColor_", "BaseSkyColor"),
    ("biomeSampler_", "BiomeSampler"),
    ("blockEntries_", "BlockEntries"),
    ("boundTexture_", "BoundTexture"),
    ("breakSession_", "BreakSession"),
    ("captureMouse_", "CaptureMouse"),
    ("charCallback_", "CharCallback"),
    ("consoleTheme_", "ConsoleTheme"),
    ("cullRevision_", "CullRevision"),
    ("currentColor_", "CurrentColor"),
    ("currentFrame_", "CurrentFrame"),
    ("deferredDown_", "DeferredDown"),
    ("faceQuadsBox_", "FaceQuadsBox"),
    ("feetAnchored_", "FeetAnchored"),
    ("generatorBtn_", "GeneratorBtn"),
    ("gridEntryIds_", "GridEntryIds"),
    ("lastAutosave_", "LastAutosave"),
    ("leftDownTime_", "LeftDownTime"),
    ("legacyHudBox_", "LegacyHudBox"),
    ("meshRevision_", "MeshRevision"),
    ("mouseButtons_", "MouseButtons"),
    ("mousePosition", "MousePosition"),
    ("onTabChanged_", "OnTabChanged"),
    ("overlayPopup_", "OverlayPopup"),
    ("prefabs_path_", "PrefabsPath"),
    ("primarySlots_", "PrimarySlots"),
    ("quitBackdrop_", "QuitBackdrop"),
    ("quitNoButton_", "QuitNoButton"),
    ("rightDownPos_", "RightDownPos"),
    ("rightPressed_", "RightPressed"),
    ("screenHeight_", "ScreenHeight"),
    ("showCrosshair", "ShowCrosshair"),
    ("solidDefault_", "SolidDefault"),
    ("speciesCache_", "SpeciesCache"),
    ("stackPadding_", "StackPadding"),
    ("stackSpacing_", "StackSpacing"),
    ("stencilZFail_", "StencilZFail"),
    ("stencilZPass_", "StencilZPass"),
    ("streamingBox_", "StreamingBox"),
    ("textRenderer_", "TextRenderer"),
    ("unloadMargin_", "UnloadMargin"),
    ("versionLabel_", "VersionLabel"),
    ("windowHeight_", "WindowHeight"),
    ("writableRoot_", "WritableRoot"),
    ("accumulator_", "Accumulator"),
    ("application_", "Application"),
    ("bodyCubeEbo_", "BodyCubeEbo"),
    ("bodyCubeVao_", "BodyCubeVao"),
    ("bodyCubeVbo_", "BodyCubeVbo"),
    ("consoleOpen_", "ConsoleOpen"),
    ("definitions_", "Definitions"),
    ("dialogFrame_", "DialogFrame"),
    ("dirtyChunks_", "DirtyChunks"),
    ("dragCursorX_", "DragCursorX"),
    ("dragCursorY_", "DragCursorY"),
    ("dragStarted_", "DragStarted"),
    ("fogMinBlend_", "FogMinBlend"),
    ("framebuffer_", "Framebuffer"),
    ("gameSession_", "GameSession"),
    ("greedyCache_", "GreedyCache"),
    ("headCubeEbo_", "HeadCubeEbo"),
    ("headCubeVao_", "HeadCubeVao"),
    ("headCubeVbo_", "HeadCubeVbo"),
    ("hotbarBuilt_", "HotbarBuilt"),
    ("hotbarCount_", "HotbarCount"),
    ("iconTexture_", "IconTexture"),
    ("initialized_", "Initialized"),
    ("inputRouter_", "InputRouter"),
    ("lastPlayerY_", "LastPlayerY"),
    ("loadChunkFn_", "LoadChunkFn"),
    ("markDirtyFn_", "MarkDirtyFn"),
    ("menuSubview_", "MenuSubview"),
    ("onBeginDrag_", "OnBeginDrag"),
    ("onInventory_", "OnInventory"),
    ("onJumpPress_", "OnJumpPress"),
    ("paletteOpen_", "PaletteOpen"),
    ("pendingQuit_", "PendingQuit"),
    ("perspective_", "Perspective"),
    ("prefabCache_", "PrefabCache"),
    ("quitMessage_", "QuitMessage"),
    ("saveChunkFn_", "SaveChunkFn"),
    ("screenWidth_", "ScreenWidth"),
    ("scrollPages_", "ScrollPages"),
    ("skinEntries_", "SkinEntries"),
    ("sneakButton_", "SneakButton"),
    ("stanceBlend_", "StanceBlend"),
    ("stencilFail_", "StencilFail"),
    ("stencilFunc_", "StencilFunc"),
    ("stencilTest_", "StencilTest"),
    ("terrainType_", "TerrainType"),
    ("touchBridge_", "TouchBridge"),
    ("verticalBtn_", "VerticalBtn"),
    ("walkCycleHz_", "WalkCycleHz"),
    ("warmupIndex_", "WarmupIndex"),
    ("warmupQueue_", "WarmupQueue"),
    ("windowHeight", "WindowHeight"),
    ("windowWidth_", "WindowWidth"),
    ("worldFolder_", "WorldFolder"),
    ("activePage_", "ActivePage"),
    ("appearance_", "Appearance"),
    ("blockCache_", "BlockCache"),
    ("blockInput_", "BlockInput"),
    ("blockWorld_", "BlockWorld"),
    ("cachedRoot_", "CachedRoot"),
    ("caveParams_", "CaveParams"),
    ("cornerHint_", "CornerHint"),
    ("draftValid_", "DraftValid"),
    ("dragActive_", "DragActive"),
    ("dragStartY_", "DragStartY"),
    ("emptyLabel_", "EmptyLabel"),
    ("flatYInput_", "FlatYInput"),
    ("flatYLabel_", "FlatYLabel"),
    ("focusOrder_", "FocusOrder"),
    ("fogEnabled_", "FogEnabled"),
    ("frameCount_", "FrameCount"),
    ("freeCursor_", "FreeCursor"),
    ("frustumBox_", "FrustumBox"),
    ("geometries_", "Geometries"),
    ("guiContext_", "GuiContext"),
    ("hoverIndex_", "HoverIndex"),
    ("iconSource_", "IconSource"),
    ("jumpButton_", "JumpButton"),
    ("keyCallback", "KeyCallback"),
    ("lastMouseX_", "LastMouseX"),
    ("lastMouseY_", "LastMouseY"),
    ("locomotion_", "Locomotion"),
    ("manualKeys_", "ManualKeys"),
    ("membership_", "Membership"),
    ("menuButton_", "MenuButton"),
    ("mouseDelta_", "MouseDelta"),
    ("mouseScroll", "MouseScroll"),
    ("presenters_", "Presenters"),
    ("quitDialog_", "QuitDialog"),
    ("sizeBlocks_", "SizeBlocks"),
    ("stencilRef_", "StencilRef"),
    ("stepUpAnim_", "StepUpAnim"),
    ("uiSettings_", "UiSettings"),
    ("windowWidth", "WindowWidth"),
    ("worldPanel_", "WorldPanel"),
    ("activeTab_", "ActiveTab"),
    ("baseTheme_", "BaseTheme"),
    ("blockDefs_", "BlockDefs"),
    ("clipStack_", "ClipStack"),
    ("clipboard_", "Clipboard"),
    ("colorMask_", "ColorMask"),
    ("creatures_", "Creatures"),
    ("deltaTime_", "DeltaTime"),
    ("depthFunc_", "DepthFunc"),
    ("depthMask_", "DepthMask"),
    ("depthTest_", "DepthTest"),
    ("draftLine_", "DraftLine"),
    ("dragMoved_", "DragMoved"),
    ("eyeHeight_", "EyeHeight"),
    ("fixedBody_", "FixedBody"),
    ("glfwWindow", "GlfwWindow"),
    ("greedyBox_", "GreedyBox"),
    ("gridSlots_", "GridSlots"),
    ("hintLabel_", "HintLabel"),
    ("hudScreen_", "HudScreen"),
    ("instances_", "Instances"),
    ("inventory_", "Inventory"),
    ("jumpSpeed_", "JumpSpeed"),
    ("lastFrame_", "LastFrame"),
    ("maxHeight_", "MaxHeight"),
    ("meshCache_", "MeshCache"),
    ("mouseDelta", "MouseDelta"),
    ("onChanged_", "OnChanged"),
    ("onConsole_", "OnConsole"),
    ("partPoses_", "PartPoses"),
    ("possessed_", "Possessed"),
    ("quadBatch_", "QuadBatch"),
    ("rootPanel_", "RootPanel"),
    ("rowHeight_", "RowHeight"),
    ("seedInput_", "SeedInput"),
    ("seedLabel_", "SeedLabel"),
    ("selAnchor_", "SelAnchor"),
    ("skinCache_", "SkinCache"),
    ("stepUpBox_", "StepUpBox"),
    ("textAlign_", "TextAlign"),
    ("textScale_", "TextScale"),
    ("textShader", "TextShader"),
    ("viewportH_", "ViewportH"),
    ("viewportW_", "ViewportW"),
    ("worldForm_", "WorldForm"),
    ("worldPage_", "WorldPage"),
    ("worldSeed_", "WorldSeed"),
    ("appPanel_", "AppPanel"),
    ("caretPos_", "CaretPos"),
    ("cavesBox_", "CavesBox"),
    ("children_", "Children"),
    ("colorTex_", "ColorTex"),
    ("cullFace_", "CullFace"),
    ("depthRbo_", "DepthRbo"),
    ("filePath_", "FilePath"),
    ("fogStart_", "FogStart"),
    ("geometry_", "Geometry"),
    ("handlers_", "Handlers"),
    ("idToName_", "IdToName"),
    ("joystick_", "Joystick"),
    ("keyStates", "KeyStates"),
    ("leftHeld_", "LeftHeld"),
    ("mainTabs_", "MainTabs"),
    ("nameToId_", "NameToId"),
    ("onEdited_", "OnEdited"),
    ("onGround_", "OnGround"),
    ("pointerX_", "PointerX"),
    ("pointerY_", "PointerY"),
    ("pointers_", "Pointers"),
    ("prevKeys_", "PrevKeys"),
    ("registry_", "Registry"),
    ("renderer_", "Renderer"),
    ("seaLevel_", "SeaLevel"),
    ("selected_", "Selected"),
    ("settings_", "Settings"),
    ("slotSize_", "SlotSize"),
    ("streamer_", "Streamer"),
    ("textures_", "Textures"),
    ("treesBox_", "TreesBox"),
    ("typeById_", "TypeById"),
    ("vertices_", "Vertices"),
    ("viewport_", "Viewport"),
    ("waterBox_", "WaterBox"),
    ("worldGen_", "WorldGen"),
    ("actions_", "Actions"),
    ("bodyYaw_", "BodyYaw"),
    ("buttons_", "Buttons"),
    ("catalog_", "Catalog"),
    ("chatLog_", "ChatLog"),
    ("checked_", "Checked"),
    ("content_", "Content"),
    ("cubeEbo_", "CubeEbo"),
    ("cubeVao_", "CubeVao"),
    ("cubeVbo_", "CubeVbo"),
    ("dragged_", "Dragged"),
    ("enabled_", "Enabled"),
    ("entries_", "Entries"),
    ("fireBox_", "FireBox"),
    ("focused_", "Focused"),
    ("headYaw_", "HeadYaw"),
    ("hotbars_", "Hotbars"),
    ("lavaBox_", "LavaBox"),
    ("loadBtn_", "LoadBtn"),
    ("logView_", "LogView"),
    ("lookPad_", "LookPad"),
    ("members_", "Members"),
    ("onClick_", "OnClick"),
    ("prefabs_", "Prefabs"),
    ("pressed_", "Pressed"),
    ("program_", "Program"),
    ("running_", "Running"),
    ("scrollY_", "ScrollY"),
    ("session_", "Session"),
    ("species_", "Species"),
    ("storage_", "Storage"),
    ("subTabs_", "SubTabs"),
    ("tooltip_", "Tooltip"),
    ("uiScale_", "UiScale"),
    ("visible_", "Visible"),
    ("agents_", "Agents"),
    ("bounds_", "Bounds"),
    ("bridge_", "Bridge"),
    ("buffer_", "Buffer"),
    ("exeDir_", "ExeDir"),
    ("fogEnd_", "FogEnd"),
    ("height_", "Height"),
    ("intent_", "Intent"),
    ("labels_", "Labels"),
    ("onMenu_", "OnMenu"),
    ("params_", "Params"),
    ("preset_", "Preset"),
    ("pressX_", "PressX"),
    ("pressY_", "PressY"),
    ("screen_", "Screen"),
    ("scroll_", "Scroll"),
    ("selEnd_", "SelEnd"),
    ("shader_", "Shader"),
    ("showHud", "ShowHud"),
    ("tabBar_", "TabBar"),
    ("visual_", "Visual"),
    ("window_", "Window"),
    ("zOrder_", "ZOrder"),
    ("baseY_", "BaseY"),
    ("blend_", "Blend"),
    ("built_", "Built"),
    ("cache_", "Cache"),
    ("coord_", "Coord"),
    ("dirty_", "Dirty"),
    ("downX_", "DownX"),
    ("downY_", "DownY"),
    ("feetY_", "FeetY"),
    ("icons_", "Icons"),
    ("input_", "Input"),
    ("items_", "Items"),
    ("label_", "Label"),
    ("panel_", "Panel"),
    ("pitch_", "Pitch"),
    ("popup_", "Popup"),
    ("skins_", "Skins"),
    ("state_", "State"),
    ("theme_", "Theme"),
    ("title_", "Title"),
    ("touch_", "Touch"),
    ("types_", "Types"),
    ("views_", "Views"),
    ("width_", "Width"),
    ("world_", "World"),
    ("byId_", "ById"),
    ("caps_", "Caps"),
    ("core_", "Core"),
    ("data_", "Data"),
    ("drag_", "Drag"),
    ("host_", "Host"),
    ("keys_", "Keys"),
    ("kind_", "Kind"),
    ("list_", "List"),
    ("mask_", "Mask"),
    ("mode_", "Mode"),
    ("open_", "Open"),
    ("root_", "Root"),
    ("seed_", "Seed"),
    ("text_", "Text"),
    ("user_", "User"),
    ("app_", "App"),
    ("ctx_", "Ctx"),
    ("egl_", "Egl"),
    ("fbo_", "Fbo"),
    ("vao_", "Vao"),
    ("vbo_", "Vbo"),
    ("yaw_", "Yaw"),
]

# Struct field renames (lowercase -> PascalCase)
STRUCT_FIELD_RENAMES = [
    (".world", ".World"),
    (".geometries", ".Geometries"),
    (".ui", ".Ui"),
    (".window", ".Window"),
    (".app", ".App"),
    ("ctx.world", "ctx.World"),
    ("ctx.geometries", "ctx.Geometries"),
    ("ctx.ui", "ctx.Ui"),
    ("ctx.window", "ctx.Window"),
    ("ctx.app", "ctx.App"),
    ("world:", "World:"),
    ("geometries:", "Geometries:"),
    ("ui:", "Ui:"),
    ("window:", "Window:"),
    ("app:", "App:"),
]


def rename_class(text: str, old: str, new: str) -> str:
    if old == new:
        return text
    if re.search(r"\bclass\s+" + re.escape(new) + r"\b", text):
        return text
    # Skip if already prefixed
    pattern = re.compile(
        r"(?<![A-Za-z0-9_])" + re.escape(old) + r"(?![A-Za-z0-9_])"
    )
    return pattern.sub(new, text)


def rename_member(text: str, old: str, new: str) -> str:
    if old == new:
        return text
    pattern = re.compile(r"\b" + re.escape(old) + r"\b")
    return pattern.sub(new, text)


def process_file(path: Path, do_classes: bool, do_members: bool, do_struct: bool) -> bool:
    if path.name in SKIP_FILES:
        return False
    try:
        original = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return False
    text = original

    if do_classes:
        for old, new in CLASS_RENAMES:
            if old.startswith("U") and old in text:
                continue
            text = rename_class(text, old, new)

    if do_members:
        # longest members first
        members = sorted(MEMBER_RENAMES, key=lambda x: len(x[0]), reverse=True)
        for old, new in members:
            if old.endswith("_") or old != new:
                text = rename_member(text, old, new)

    if do_struct:
        for old, new in STRUCT_FIELD_RENAMES:
            text = text.replace(old, new)

    if text != original:
        path.write_text(text, encoding="utf-8", newline="\n")
        return True
    return False


def main():
    do_classes = "--classes" in sys.argv or len(sys.argv) == 1
    do_members = "--members" in sys.argv or len(sys.argv) == 1
    do_struct = "--struct" in sys.argv or len(sys.argv) == 1

    changed = []
    for path in sorted(ROOT.rglob("*")):
        if path.suffix not in (".h", ".cpp"):
            continue
        if process_file(path, do_classes, do_members, do_struct):
            changed.append(str(path.relative_to(ROOT.parent)))

    print(f"Updated {len(changed)} files")
    for p in changed[:50]:
        print(f"  {p}")
    if len(changed) > 50:
        print(f"  ... and {len(changed) - 50} more")


if __name__ == "__main__":
    main()
