#!/usr/bin/env python3
"""Runtime verification matrix: spawn, wander, art columns per species."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

TOOLS = Path(__file__).resolve().parent
ROOT = TOOLS.parent
MODELS = ROOT / "models" / "creatures"
DOCS = ROOT / "docs"
LOG_PATH = TOOLS / "creature_resolution_log.yaml"
AUDIT_PATH = TOOLS / "creature_audit_status.yaml"
SPAWN_DIAG = TOOLS / "creature_spawn_diagnosis.yaml"


def load_yaml(path: Path) -> dict:
    if not path.is_file():
        return {}
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def main() -> None:
    log = load_yaml(LOG_PATH).get("species") or {}
    audit = load_yaml(AUDIT_PATH).get("species") or {}
    spawn = load_yaml(SPAWN_DIAG).get("species") or {}

    rows = []
    for species_dir in sorted(MODELS.iterdir()):
        if not species_dir.is_dir():
            continue
        path = species_dir / "creature.json"
        if not path.is_file():
            continue
        creature = json.loads(path.read_text(encoding="utf-8"))
        sid = creature["id"]
        entry = log.get(sid, {})
        aud = audit.get(sid, {})
        sp = spawn.get(sid, {})
        rows.append(
            {
                "id": sid,
                "spawnable": creature.get("catalog", {}).get("spawnable", False),
                "habitat": creature.get("habitat"),
                "spawn_status": entry.get("spawn", {}).get("status", "pending"),
                "wander_status": entry.get("wander", {}).get("status", "pending"),
                "silhouette_status": entry.get("silhouette", {}).get("status", "pending"),
                "icon_status": entry.get("icon", {}).get("status", "pending"),
                "asset_tier": aud.get("asset_tier", "?"),
                "parts_profile": aud.get("parts_profile", "?"),
                "icon_quality": aud.get("icon_quality", "?"),
                "eye_offset_error": sp.get("eye_offset_error", ""),
                "issues_open": len(entry.get("issues_open") or []),
            }
        )

    out = DOCS / "CREATURE_VERIFICATION_MATRIX.md"
    lines = [
        "# Creature verification matrix",
        "",
        "Generated by `tools/verify_creature_runtime.py`.",
        "",
        "| id | habitat | spawn | wander | silhouette | icon | asset | parts | icon_q | open |",
        "|----|---------|-------|--------|------------|------|-------|-------|--------|------|",
    ]
    for r in rows:
        if not r["spawnable"]:
            continue
        lines.append(
            f"| {r['id']} | {r['habitat']} | {r['spawn_status']} | {r['wander_status']} "
            f"| {r['silhouette_status']} | {r['icon_status']} | {r['asset_tier']} "
            f"| {r['parts_profile']} | {r['icon_quality']} | {r['issues_open']} |"
        )
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"OK verification matrix -> {out.name}")


if __name__ == "__main__":
    main()
