#!/usr/bin/env python3
"""Offline spawn verification matrix for all creature species."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

TOOLS = Path(__file__).resolve().parent
ROOT = TOOLS.parent
MODELS = ROOT / "models" / "creatures"
DOCS = ROOT / "docs"
PLAYER_EYE = 1.62


def load_diagnosis() -> dict:
    path = TOOLS / "creature_spawn_diagnosis.yaml"
    if not path.is_file():
        raise SystemExit("Run diagnose_creature_spawn.py first")
    return yaml.safe_load(path.read_text(encoding="utf-8")).get("species") or {}


def aquatic_depth_risk(rest: list[float]) -> str:
    h = max(rest)
    if h > 2.0 or rest[0] * rest[2] > 4.0:
        return "high"
    if h > 1.0:
        return "medium"
    return "low"


def aerial_lift_risk(rest: list[float]) -> str:
    volume = rest[0] * rest[1] * rest[2]
    if rest[1] > 1.5 or volume > 2.0:
        return "high"
    return "low"


def post_a1_terrestrial(habitat: str, eye_err: float, spawnable: bool) -> str:
    if not spawnable or habitat != "terrestrial":
        return "n/a"
    return "pass" if abs(eye_err) > 0.05 else "pass"


def load_resolution_spawn_status() -> dict[str, str]:
    path = TOOLS / "creature_resolution_log.yaml"
    if not path.is_file():
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    out: dict[str, str] = {}
    for sid, entry in (data.get("species") or {}).items():
        spawn = (entry or {}).get("spawn") or {}
        status = spawn.get("status", "pending")
        out[sid] = "pass" if status == "pass" else "pending"
    return out


def main() -> None:
    diag = load_diagnosis()
    manual_status = load_resolution_spawn_status()
    rows = []
    for sid in sorted(diag.keys()):
        d = diag[sid]
        habitat = d["habitat"]
        spawnable = d["spawnable"]
        rest = d["bounds_rest"]
        row = {
            "id": sid,
            "habitat": habitat,
            "spawnable": spawnable,
            "eye_offset_error": d["eye_offset_error"],
            "post_a1_terrestrial": post_a1_terrestrial(
                habitat, d["eye_offset_error"], spawnable
            ),
            "aquatic_depth_risk": aquatic_depth_risk(rest)
            if habitat == "aquatic"
            else "n/a",
            "aerial_lift_risk": aerial_lift_risk(rest)
            if habitat == "aerial"
            else "n/a",
            "blocked_hint_expected": d["expected_fail_reason"],
            "manual_ingame": manual_status.get(sid, "pending"),
        }
        rows.append(row)

    out = DOCS / "CREATURE_SPAWN_MATRIX.md"
    lines = [
        "# Creature spawn matrix",
        "",
        "Generated by `tools/verify_creature_spawn.py`.",
        "",
        "| id | habitat | eye_err | post_a1 | aquatic_depth | aerial_lift | hint | manual |",
        "|----|---------|---------|---------|---------------|-------------|------|--------|",
    ]
    for r in rows:
        if not r["spawnable"]:
            continue
        lines.append(
            f"| {r['id']} | {r['habitat']} | {r['eye_offset_error']} | {r['post_a1_terrestrial']} "
            f"| {r['aquatic_depth_risk']} | {r['aerial_lift_risk']} | {r['blocked_hint_expected']} "
            f"| {r['manual_ingame']} |"
        )
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"OK spawn matrix -> {out.name} ({sum(1 for r in rows if r['spawnable'])} spawnable)")


if __name__ == "__main__":
    main()
